### ISSUE TITLE
Tiles do not draw correctly with current syntax

### ISSUE THREAD

**Issue by larfylarf** [larfylarf/COSC3011-TileGame#9]
Tile class looks good so far! 

Can't seem to get the tiles to draw at all using this syntax:
```Java
public Tile(int pos, GameWindow gameW){
  //...
super(new ImageIcon(GameWindow.TILE_IMAGE+"gold.gif"));
  //...
}
```

However, if I change up the method that we use to read the files, the following adjustments allow the tiles to be drawn and interacted with: 
```Java
public static final String TILE_IMAGE = "/TileImages/";
```
```Java
public Tile(int pos, GameWindow gameW){
  //...
super(new ImageIcon(JPanel.class.getResource(GameWindow.TILE_IMAGE+"gold.gif")));
  //...
}
```

Verified that TileImages folder is included in build. All .gif images are located in the folder and seemingly are being referenced properly.

Is anybody else having this issue? Mac vs. Windows thing? Could totally be something I'm doing wrong with Eclipse.

Win10 Pro x64, Java JDK 8v74, Eclipse MARS.1

**Comment by violaceousfox** [comment]
Same problem for me. I'm on win 7 with java 8.72. Maybe its the way we imported the files from github? Your solution throws a null pointer exception for me, but getting rid of "`GameWindow`" in

`super(new ImageIcon(JPanel.class.getResource(GameWindow.TILE_IMAGE+"gold.gif")));`

makes it work properly.

**Comment by larfylarf** [comment]
Awesome! Yeah, this looks like it works for me as well. Note sure what is going on - I know the original method worked before, since I used it in my version of the card game from last year....

**Comment by larfylarf** [comment]
Thank you, @violaceousfox, by the way! We can resolve the branch if needed - we should probably make sure it works for everybody before closing this out.
